%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(agent_thrift).
-behaviour(thrift_service).


-include("agent_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% emitBatch(This, Batch)
function_info('emitBatch', params_type) ->
  {struct, [{1, {struct, {'jaeger_types', 'Batch'}}}]}
;
function_info('emitBatch', reply_type) ->
  oneway_void;
function_info('emitBatch', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

