%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(collector_thrift).
-behaviour(thrift_service).


-include("collector_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% submitBatches(This, Batches)
function_info('submitBatches', params_type) ->
  {struct, [{1, {list, {struct, {'jaeger_types', 'Batch'}}}}]}
;
function_info('submitBatches', reply_type) ->
  {list, {struct, {'jaeger_types', 'BatchSubmitResponse'}}};
function_info('submitBatches', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

