%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(jaeger_types).

-include("jaeger_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('Tag') ->
  {struct, [{1, string},
          {2, i32},
          {3, string},
          {4, double},
          {5, bool},
          {6, i64},
          {7, string}]}
;

struct_info('Log') ->
  {struct, [{1, i64},
          {2, {list, {struct, {'jaeger_types', 'Tag'}}}}]}
;

struct_info('SpanRef') ->
  {struct, [{1, i32},
          {2, i64},
          {3, i64},
          {4, i64}]}
;

struct_info('Span') ->
  {struct, [{1, i64},
          {2, i64},
          {3, i64},
          {4, i64},
          {5, string},
          {6, {list, {struct, {'jaeger_types', 'SpanRef'}}}},
          {7, i32},
          {8, i64},
          {9, i64},
          {10, {list, {struct, {'jaeger_types', 'Tag'}}}},
          {11, {list, {struct, {'jaeger_types', 'Log'}}}}]}
;

struct_info('Process') ->
  {struct, [{1, string},
          {2, {list, {struct, {'jaeger_types', 'Tag'}}}}]}
;

struct_info('Batch') ->
  {struct, [{1, {struct, {'jaeger_types', 'Process'}}},
          {2, {list, {struct, {'jaeger_types', 'Span'}}}}]}
;

struct_info('BatchSubmitResponse') ->
  {struct, [{1, bool}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('Tag') ->
  {struct, [{1, required, string, 'key', undefined},
          {2, required, i32, 'vType', undefined},
          {3, optional, string, 'vStr', undefined},
          {4, optional, double, 'vDouble', undefined},
          {5, optional, bool, 'vBool', undefined},
          {6, optional, i64, 'vLong', undefined},
          {7, optional, string, 'vBinary', undefined}]}
;

struct_info_ext('Log') ->
  {struct, [{1, required, i64, 'timestamp', undefined},
          {2, required, {list, {struct, {'jaeger_types', 'Tag'}}}, 'fields', []}]}
;

struct_info_ext('SpanRef') ->
  {struct, [{1, required, i32, 'refType', undefined},
          {2, required, i64, 'traceIdLow', undefined},
          {3, required, i64, 'traceIdHigh', undefined},
          {4, required, i64, 'spanId', undefined}]}
;

struct_info_ext('Span') ->
  {struct, [{1, required, i64, 'traceIdLow', undefined},
          {2, required, i64, 'traceIdHigh', undefined},
          {3, required, i64, 'spanId', undefined},
          {4, required, i64, 'parentSpanId', undefined},
          {5, required, string, 'operationName', undefined},
          {6, optional, {list, {struct, {'jaeger_types', 'SpanRef'}}}, 'references', []},
          {7, required, i32, 'flags', undefined},
          {8, required, i64, 'startTime', undefined},
          {9, required, i64, 'duration', undefined},
          {10, optional, {list, {struct, {'jaeger_types', 'Tag'}}}, 'tags', []},
          {11, optional, {list, {struct, {'jaeger_types', 'Log'}}}, 'logs', []}]}
;

struct_info_ext('Process') ->
  {struct, [{1, required, string, 'serviceName', undefined},
          {2, optional, {list, {struct, {'jaeger_types', 'Tag'}}}, 'tags', []}]}
;

struct_info_ext('Batch') ->
  {struct, [{1, required, {struct, {'jaeger_types', 'Process'}}, 'process', #'Process'{}},
          {2, required, {list, {struct, {'jaeger_types', 'Span'}}}, 'spans', []}]}
;

struct_info_ext('BatchSubmitResponse') ->
  {struct, [{1, required, bool, 'ok', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

